KMGames.Web/Models/SessionCart/ItemCart.cs
using KMGames.Entities.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KMGames.Web.Models.SessionCart
{
    public class ItemCart
    {
        //------------PROPERTIES-----------//

        public int GameId { get; set; }

        public string Title { get; set; }

        public decimal ActualPrice { get; set; }

        public string Image { get; set; }

        public string Description { get; set; }

        //----------CONSTRUCTOR----------//

        public ItemCart() { }

        public ItemCart(Game game)
        {
            GameId = game.GameId;
            Title = game.Title;
            ActualPrice = game.ActualPrice;
            Image = game.Image;
            Description = game.Description;
        }
    }
}

KMGames.Web/Models/SessionCart/SessionCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KMGames.Web.Models.SessionCart
{
    public class SessionCart
    {
        //----------PROPERTIES----------//

        public List<ItemCart> Items { get; set; }

        public string LastCategory { get; set; }

        //----------CONSTRUCTOR----------//

        public SessionCart()
        {
            Items = new List<ItemCart>();
        }

        //----------METHODS----------//

        public int Count()
        {
            return Items.Count;
        } 

        public void AddGame(ItemCart game)
        {
            Items.Add(game);
        }

        public void Clear()
        {
            Items.Clear();
        }

        
        public void RemoveGame(int id)
        {
            Items.Remove(Items.First(i => i.GameId == id));
        }
    }
}

KMGames.Web/Controllers/BuyableController.cs
using AutoMapper;
using KMGames.Entities.DTOs.GameDTO;
using KMGames.Entities.Entities;
using KMGames.Services.Interfaces;
using KMGames.Web.App_Start;
using KMGames.Web.ViewModel.Buyables;
using KMGames.Web.ViewModel.Categories;
using KMGames.Web.ViewModel.Games;
using KMGames.Web.ViewModel.PlayerType;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KMGames.Web.Controllers
{
    public class BuyableController : Controller
    {
        //----------PROPERTIES----------//

        private readonly IGameService _gameService;
        private readonly ICategoryService _categoryService;
        private readonly IPLayerTypeService _typesService;


        private readonly IMapper _mapper;

        //----------CONTRUCTOR----------//

        public BuyableController(IGameService gameService, ICategoryService categoryService, IPLayerTypeService playerTypes)
        {
            _gameService = gameService;
            _categoryService = categoryService;
            _typesService = playerTypes;

            _mapper = AutoMapperConfig.Mapper;
        }

        // GET: Buyable
        public ActionResult Index(string filter = null)
        {

            List<GameListDto> games;
            Category category;
            List<GameListVm> gamesListVm;

            category = _categoryService.GetCategory(filter);

            if(category is null)
            {
                games = _gameService.GetGames().ToList();
            }
            else
            {
                games = _gameService.GetGamesByCategory(category.CategoryId);
            }

            gamesListVm = _mapper.Map<List<GameListVm>>(games);

            BuyableGameListVm buyableGames = new BuyableGameListVm
            {
                Games = gamesListVm,
                Categories = _mapper.Map<List<CategoryListVm>>(_categoryService.GetCategories()),
                PlayersGame = _mapper.Map<List<PlayerTypeListVm>>(_typesService.GetPlayerTypes()),
                Filter = category
            };

            return View(buyableGames);
        }

        public ActionResult Details(int? gameId, string filter)
        {
            if(gameId is null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            var game = _gameService.GetGame(gameId.Value);

            if(game is null)
            {
                TempData["Error"] = "ERROR: This game doesn't exist or isn't for sale.";

                return RedirectToAction("Index");
            }

            BuyableDetailsVm buyableGame = new BuyableDetailsVm()
            {
                Game = _mapper.Map<GameListVm>(game),
                Categories = _mapper.Map<List<CategoryListVm>>(_categoryService.GetCategoriesFrom(gameId.Value)),
                PlayerTypes = _mapper.Map<List<PlayerTypeListVm>>(_typesService.GetPlayerTypesFrom(gameId.Value)),
                Filter = filter
            };

            return View(buyableGame);
        }
    }
}

KMGames.Web/Controllers/CartController.cs
using AutoMapper;
using KMGames.Entities.Entities;
using KMGames.Services.Interfaces;
using KMGames.Web.App_Start;
using KMGames.Web.Models.Cart;
using KMGames.Web.ViewModel.Cart;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KMGames.Web.Controllers
{
    public class CartController : Controller
    {
        //----------PROPERTIES----------//

        private Cart _cart;

        private IGameService _gameService;
        private ISaleService _saleService;
        private IUserService _userService;

        private IMapper _mapper;

        //----------CONSTRUCTOR----------/

        public CartController(IGameService gameService, ISaleService saleService, IUserService userService)
        {
            _gameService = gameService;
            _saleService = saleService;
            _userService = userService;

            _mapper = AutoMapperConfig.Mapper;
        }

        //----------METHODS----------//

        private Cart GetCart()
        {
            if(_cart != null)
            {
                return _cart;
            }

            _cart = (Cart)Session["cart"];

            if(_cart is null)
            {
                _cart = new Cart();
                Session["cart"] = _cart;
            }

            return _cart;
        }

        // GET: Index

        public ActionResult Index()
        {
            _cart = GetCart();

            if(_cart.Count() == 0)
            {
                return View("EmptyCart");
            }

            List<ItemCartVm> items = _mapper.Map<List<ItemCartVm>>(_cart.Items());

            CartVm cart = new CartVm()
            {
                Items = items,
                LastCategory = _cart.LastCategory
            };

            return View(cart);
        }

        // GET: Cart
        public ActionResult ShowCart()
        {
            _cart = GetCart();

            return PartialView("_ShoppingCart",_cart);
        }

        public ActionResult AddGame(int? gameId, string category)
        {
            if(gameId is null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            var game = _gameService.GetGame(gameId.Value);

            if(game is null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.NotFound);
            }

            _cart = GetCart();

            ItemCart item = new ItemCart(game);

            _cart.AddGame(item);

            _cart.LastCategory = category;

            Session["cart"] = _cart; 

            return RedirectToAction("Index");
        }

        public ActionResult RemoveGame(int? gameId)
        {
            if(gameId is null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            _cart = GetCart();

            _cart.RemoveGame(gameId.Value);

            Session["cart"] = _cart;

            return RedirectToAction("Index");
        }

        public ActionResult PayCart()
        {
            _cart = GetCart();

            var user = _userService.GetUserByEmail(User.Identity.Name);

            var games = _mapper.Map<List<Game>>(_cart.Items());

            try
            {
                _saleService.PayGames(user, games);

                _cart.Clear();

                Session["cart"] = _cart;

                TempData["Success"] = "SUCCESS: Payment was sucessful.";

                return View("EmptyCart");
            }
            catch (Exception)
            {
                TempData["Error"] = "ERROR: Something wrong happened.";

                return View("Index");
            }

        }
    }
}

KMGames.Web/Controllers/SessionCartController.cs
using AutoMapper;
using KMGames.Entities.Entities;
using KMGames.Services.Interfaces;
using KMGames.Web.App_Start;
using KMGames.Web.Models.SessionCart;
using KMGames.Web.ViewModel.SessionCart;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KMGames.Web.Controllers
{
    public class SessionCartController : Controller
    {
        //----------PROPERTIES----------//

        private SessionCart _cart;

        private IGameService _gameService;
        private ISaleService _saleService;
        private IUserService _userService;
        private ICartService _cartService;

        private IMapper _mapper;

        //----------CONSTRUCTOR----------/

        public SessionCartController(IGameService gameService, ISaleService saleService, IUserService userService, ICartService cartService)
        {
            _gameService = gameService;
            _saleService = saleService;
            _userService = userService;
            _cartService = cartService;

            _mapper = AutoMapperConfig.Mapper;
        }

        //----------METHODS----------//

        private SessionCart GetCart()
        {
            _cart = (SessionCart)Session["cart"];

            if(_cart is null)
            {
                _cart = new SessionCart();

                if (_cartService.HasItems(User.Identity.GetUserId()))
                {
                    var cart = _cartService.GetCart(User.Identity.GetUserId());

                    _cart.Items = _mapper.Map<List<ItemCart>>(cart.Items);
                }

                Session["cart"] = _cart;
            }

            return _cart;
        }

        // GET: Index

        public ActionResult Index()
        {
            _cart = GetCart();

            if(_cart.Count() == 0)
            {
                return View("EmptyCart");
            }

            List<ItemCartVm> items = _mapper.Map<List<ItemCartVm>>(_cart.Items);

            CartVm cart = new CartVm()
            {
                Items = items,
                LastCategory = _cart.LastCategory
            };

            return View(cart);
        }

        // GET: SessionCart
        public ActionResult ShowCart()
        {
            _cart = GetCart();

            return PartialView("_ShoppingCart",_cart);
        }

        public ActionResult AddGame(int? gameId, string category)
        {
            if(gameId is null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            var game = _gameService.GetGame(gameId.Value);

            if(game is null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.NotFound);
            }

            _cart = GetCart();

            ItemCart item = new ItemCart(game);

            _cart.AddGame(item);

            _cart.LastCategory = category;

            if (_cart.Count() == 1)
            {
                _cartService.CreateCart(User.Identity.GetUserId(), game);
            }
            else
            {
                _cartService.AddGameToCart(User.Identity.GetUserId(), game);
            }

            Session["cart"] = _cart; 

            return RedirectToAction("Index");
        }

        public ActionResult RemoveGame(int? gameId)
        {
            if(gameId is null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            _cart = GetCart();

            _cart.RemoveGame(gameId.Value);

            Session["cart"] = _cart;

            if(_cart.Count() == 0)
            {
                _cartService.RemoveCartFrom(User.Identity.GetUserId());
            }
            else
            {
                _cartService.RemoveGameFromCart(User.Identity.GetUserId(), gameId.Value);
            }

            return RedirectToAction("Index");
        }

        public ActionResult PayCart()
        {
            _cart = GetCart();

            var user = _userService.GetUserByEmail(User.Identity.Name);

            var games = _mapper.Map<List<Game>>(_cart.Items);

            try
            {
                _saleService.PayGames(user, games);

                _cart.Clear();

                _cartService.ClearCartFor(User.Identity.GetUserId());

                Session["cart"] = _cart;

                TempData["Success"] = "SUCCESS: Payment was sucessful.";

                return View("EmptyCart");
            }
            catch (Exception)
            {
                TempData["Error"] = "ERROR: Something wrong happened.";

                return View("Index");
            }

        }
    }
}

KMGames.Web/Views/SessionCart/EmptyCart.cshtml
@{
    ViewBag.Title = "EmptyCart";
}

<h2>Shopping Cart</h2>

<div class="alert alert-dark alert-dismissible d-flex align-items-center w-75 fade show" role="alert">
    There's no game on your shopping cart.
    @*<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>*@
</div>
<div>
    <a class="btn btn-sm btn-outline-success bg-success bg-opacity-10 me-2" href="@Url.Action("Index","Buyable")">
        <i class="fa fa-check"></i>
        Buy
    </a>
    <a class="btn btn-sm btn-outline-danger bg-danger bg-opacity-10" href="@Url.Action("Index","Home")">
        <i class="fa fa-undo"></i>
            Home
    </a>
</div>

KMGames.Web/Views/SessionCart/Index.cshtml
@model KMGames.Web.ViewModel.SessionCart.CartVm

@{
    ViewBag.Title = "Index";
}

<div class="w-100 mb-3 text-center">
    <h2>
        Your Shopping Cart
    </h2>
</div>

<div class="container">
    <table class="w-75">
        <thead>
        </thead>
        <tbody>
            @foreach (var item in Model.Items)
            {
                <tr>
                    <td>
                        @if (item.Image is null)
                        {
                            <img class="rounded-2 mb-3" src="@Url.Content(KMGames.Utilities.WC.GameImageNotAvailable)" style="width:260px; height:80px;" />
                        }
                        else
                        {
                            <img class="rounded-2 mb-3" src="@Url.Content(KMGames.Utilities.WC.GameImagesFolder+item.Image)" style="width:260px; height:80px" />
                        }
                    </td>
                    <td class="w-50" style="text-align:center">
                        @Html.DisplayFor(_ => item.Title)
                    </td>
                    <td style="text-align:center">
                        @Html.DisplayFor(_ => item.ActualPrice)
                    </td>
                    <td>
                        @*<a class="btn btn-sm btn-outline-danger bg-opacity-25 bg-danger col-12" href="@Url.Action("RemoveGame", "Cart", new {gameId = item.GameId})">
                                <i class="fa fa-trash"></i>
                                Remove
                            </a>*@

                        <form action="@Url.Action("RemoveGame","SessionCart")" id="removeForm">

                            @Html.Hidden("gameId",item.GameId)

                            <button class="btn btn-sm btn-outline-danger bg-opacity-25 bg-danger col-12" type="submit"
                                    onclick="return RemoveConfirmed('@item.Title')">
                                <i class="fa fa-trash"></i>
                                Remove
                            </button>

                        </form>
                    </td>
                </tr>
            }
            <tr>
                <td></td>
                <td class="w-50 fw-bold" style="text-align:center">
                    TOTAL  :
                </td>
                <td class="fw-bold" style="text-align:center">
                    @Model.Items.Sum(i => i.ActualPrice).ToString("C")
                </td>
            </tr>
        </tbody>
    </table>
    <div class="mt-3  d-flex">
        <a class="btn bg-opacity-25 btn-outline-success col-2 me-lg-3" href="@Url.Action("Index","Buyable", new {filter = Model.LastCategory})">
            <i class="fa fa-shopping-cart"></i>
            Keep Buying
        </a>

        <form action="@Url.Action("PayCart","SessionCart")" id="payForm" class="w-75">

            <button class="btn bg-opacity-25 btn-outline-primary col-3" type="submit"
                    onclick="return PayConfirmed('@Model.Items.Sum(g => g.ActualPrice).ToString("C")')">
                <i class="fa fa-dollar-sign"></i>
                Pay
            </button>
        </form>

    </div>
</div>

@section scripts
{
    <script>
        function RemoveConfirmed(title) {
            Swal.fire({
                title: 'Remove from your shopping cart',
                text: "Do you want to remove this game: " + title + " ?",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Remove',
                cancelButtonText: 'Cancel'
            }).then((result) => {

                if (result.isConfirmed) {
                    document.getElementById('removeForm').submit();
                }

            })
            return false;
        }
    </script>

    <script>
        function PayConfirmed(money) {
            Swal.fire({
                title: 'Pay cart',
                text: "You are going to pay: " + money,
                icon: 'info',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Pay!'
            }).then((result) => {
                if (result.isConfirmed) {
                    //Swal.fire(
                    //    'Deleted!',
                    //    'Your file has been deleted.',
                    //    'success'
                    //)
                    document.getElementById('payForm').submit();
                }
            })

            return false
        }
    </script>

}