KMGames.Web/Controllers/GamesController.cs
using AutoMapper;
using KMGames.Data.Migrations;
using KMGames.Entities.DTOs.PlayerType;
using KMGames.Entities.Entities;
using KMGames.Services.Interfaces;
using KMGames.Utilities;
using KMGames.Web.App_Start;
using KMGames.Web.ViewModel.Categories;
using KMGames.Web.ViewModel.Games;
using KMGames.Web.ViewModel.PlayerType;
using Microsoft.Ajax.Utilities;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Mapping;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;

namespace KMGames.Web.Controllers
{
    [Authorize]
    public class GamesController : Controller
    {

        //----------PROPERTIES----------//

        private readonly IGameService _gameService;
        private readonly IDeveloperService _developerService;
        private readonly ICategoryService _categoryService;
        private readonly IPLayerTypeService _playerTypeService;

        private readonly IMapper _mapper;

        //----------CONSTRUCTOR----------//

        public GamesController(IGameService gameService, IDeveloperService developer,
                ICategoryService categoryService, IPLayerTypeService pLayerTypeService)
        {
            _gameService = gameService;
            _developerService = developer;
            _categoryService = categoryService;
            _playerTypeService = pLayerTypeService;

            _mapper = AutoMapperConfig.Mapper;
        }

        //----------METHODS----------//

        private void LoadSelected(List<CategoryCheckVm> categories, ICollection<GameCategory> selected)
        {
            foreach(var item in selected)
            {
                categories.FirstOrDefault(c => c.CategoryId == item.CategoryId).Selected = true;
            }
        }

        private void LoadSelected(List<PlayerTypeCheckVm> types, ICollection<PlayerGame> selected)
        {
            foreach (var item in selected)
            {
                types.FirstOrDefault(c => c.PlayerTypeId == item.PlayerTypeId).Selected = true;
            }
        }

        //----------ACTIONS----------//

        // GET: Games
        public ActionResult Index(int? page, int? pageSize)
        {
            var gamesList = _gameService.GetGames();

            var gameListVm = _mapper.Map<List<GameListVm>>(gamesList);

            page = page ?? 1;
            pageSize = pageSize ?? 10;

            ViewBag.PageSize = pageSize;

            return View(gameListVm.ToPagedList(page.Value,pageSize.Value));
        }

        public ActionResult Create()
        {
            var categories = _categoryService.GetCheckBoxList();

            var categoriesCheckVm = _mapper.Map<List<CategoryCheckVm>>(categories);

            var types = _playerTypeService.GetCheckBoxList();

            var typesCheckVm = _mapper.Map<List<PlayerTypeCheckVm>>(types);

            var gameEditVm = new GameEditVm()
            {
                Developers = _developerService.GetDropDownList(),
                Categories = categoriesCheckVm,
                PlayerTypes = typesCheckVm,
                Release = DateTime.Now.Date
            };

            return View(gameEditVm);
        }

        [HttpPost]
        public ActionResult Create(GameEditVm gameEditVm)
        {
            if (!ModelState.IsValid)
            {
                gameEditVm.Developers = _developerService.GetDropDownList();

                return View(gameEditVm);
            }

            var game = _mapper.Map<Game>(gameEditVm);

            if (_gameService.Exist(game))
            {
                gameEditVm.Developers = _developerService.GetDropDownList();

                return View(gameEditVm);
            }

            List<GameCategory> gameCategories = new List<GameCategory>();
            List<PlayerGame> playersGames = new List<PlayerGame>();

            gameEditVm.Categories.ForEach(c =>
            {
                if (c.Selected) gameCategories.Add(new GameCategory() { CategoryId = c.CategoryId });
            });

            gameEditVm.PlayerTypes.ForEach(pg =>
            {
                if (pg.Selected) playersGames.Add(new PlayerGame() { PlayerTypeId = pg.PlayerTypeId });
            });

            game.GameCategories = gameCategories;
            game.PlayersGame = playersGames; 
            
            try 
            {
                if (gameEditVm.imageFile != null)
                {
                    string extension = Path.GetExtension(gameEditVm.imageFile.FileName);
                    string filename = Guid.NewGuid().ToString();
                    var file = $"{filename}{extension}";
                    var response = FileHelper.UploadPhoto(gameEditVm.imageFile, WC.GameImagesFolder, file);
                    game.Image = file;
                }

                _gameService.Add(game);
                TempData["Success"] = "SUCCESS: Game added successfully.";
            }
            catch (Exception ex)
            {
                TempData["Error"] = $"ERROR: An error ocurred while trying to save data.\n{ex.Message}";

                gameEditVm.Developers = _developerService.GetDropDownList();

                return View(gameEditVm);
            }

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? id)
        {
            if(id is null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            var game = _gameService.GetGame(id.Value);

            if (game == null)
            {
                TempData["Error"] = "ERROR: This game was deleted by other user. It can't be deleted.";

                return RedirectToAction("Index");
            }

            var categories = _categoryService.GetCheckBoxList();
            var categoriesVm = _mapper.Map<List<CategoryCheckVm>>(categories);

            var types = _playerTypeService.GetCheckBoxList();
            var typesVm = _mapper.Map<List<PlayerTypeCheckVm>>(types);

            var developers = _developerService.GetDropDownList();
            var developersVm = _mapper.Map<List<SelectListItem>>(developers);

            LoadSelected(categoriesVm, game.GameCategories);
            LoadSelected(typesVm, game.PlayersGame);

            var gameEditVm = _mapper.Map<GameEditVm>(game);

            gameEditVm.Developers = developersVm;
            gameEditVm.Categories = categoriesVm;
            gameEditVm.PlayerTypes = typesVm;

            return View(gameEditVm);
        }

        [HttpPost]
        public ActionResult Edit(GameEditVm gameEditVm)
        {
            if (!ModelState.IsValid)
            {
                gameEditVm.Developers = _developerService.GetDropDownList();

                return View(gameEditVm);
            }

            gameEditVm.GameCategories = new List<GameCategory>();
            gameEditVm.PlayersGame = new List<PlayerGame>();

            gameEditVm.Categories.ForEach(c =>
            {
                if (c.Selected) gameEditVm.GameCategories.Add(new GameCategory() { CategoryId = c.CategoryId });
            });

            gameEditVm.PlayerTypes.ForEach(pg =>
            {
                if (pg.Selected) gameEditVm.PlayersGame.Add(new PlayerGame() { PlayerTypeId = pg.PlayerTypeId });
            });

            var game = _mapper.Map<Game>(gameEditVm);

            if (_gameService.Exist(game))
            {
                gameEditVm.Developers = _developerService.GetDropDownList();

                return View(gameEditVm);
            }

            try
            {
                if(gameEditVm.imageFile != null)
                {
                    if (gameEditVm.Image != null)
                    {
                        FileHelper.DeletePhoto(WC.GameImagesFolder+gameEditVm.Image);
                    }

                    var extension = Path.GetExtension(gameEditVm.imageFile.FileName);
                    var fileName = Guid.NewGuid().ToString();
                    var file = $"{fileName}{extension}";
                    var response = FileHelper.UploadPhoto(gameEditVm.imageFile, WC.GameImagesFolder, file);
                    game.Image = file;
                }

                _gameService.Edit(game);

                TempData["Success"] = "SUCCESS: Game edited successfully";

            }
            catch (Exception ex)
            {
                TempData["Error"] = $"ERROR: An error ocurred while trying to edit game.\n{ex.Message}";
            }

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int? id)
        {
            if(id is null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            var game = _gameService.GetGame(id.Value);

            if(game is null)
            {
                TempData["Error"] = "ERROR: This game was deleted by other user.";

                return RedirectToAction("Index");
            }
            else if (_gameService.ItsRelated(id.Value))
            {
                TempData["Error"] = "ERROR: This game is related to some sales.";

                return RedirectToAction("Index");
            }

            var gameListVm = _mapper.Map<GameListVm>(game);

            return View(gameListVm);
        }

        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var game = _gameService.GetGame(id);

            try
            {
                if(game.Image != null)
                {
                    FileHelper.DeletePhoto(WC.GameImagesFolder + game.Image);
                }

                _gameService.Delete(game);

                TempData["Warning"] = $"WARNING: {game.Title} deleted successfully";
            }
            catch(Exception ex)
            {

KMGames.Web/Views/Games/Create.cshtml
@model KMGames.Web.ViewModel.Games.GameEditVm
@{

    ViewBag.Title = "Create";
}

<h2>Add game</h2>

@using (Html.BeginForm("Create", "Games", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()


    <div class="container form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="mt-3 text-start align-content-start">
            <div class="row">
                <div class="col">
                    <div class="form-group mt-3">
                        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group mt-3">
                        @Html.LabelFor(model => model.ActualPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ActualPrice, new { htmlAttributes = new { @class = "form-control", } })
                            @Html.ValidationMessageFor(model => model.ActualPrice, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group mt-3">
                        @Html.LabelFor(model => model.Release, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div>
                            @Html.TextBoxFor(model => model.Release, "{0:yyyy-MM-dd}", new
                            {
                                @class = "form-control",
                                @Type = "date"
                                //@value = D,
                                //@min = "2018-06-07T00:00",
                                //@max = DateTime.Today.ToShortDateString()
                            })
                            @Html.ValidationMessageFor(model => model.Release, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group mt-3">
                        @Html.LabelFor(model => model.DeveloperId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.DeveloperId, Model.Developers, "Select a developer", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.DeveloperId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group mt-3 col-lg-7">
                        @Html.LabelFor(model => model.Categories, htmlAttributes: new { @class = "control-label" })
                        <ul class="list-group">
                            @for (int i = 0; i < Model.Categories.Count; i++)
                            {
                                <li class="list-group-item">
                                    <div class="form-check form-switch">
                                        @Html.HiddenFor(m => m.Categories[i].CategoryId)
                                        @Html.HiddenFor(m => m.Categories[i].Category)
                                        @Html.CheckBoxFor(m => m.Categories[i].Selected, new { @class = "form-check-input", @type = "checkbox", @role = "switch" })
                                        @Html.LabelFor(m => m.Categories[i].Selected, Model.Categories[i].Category, new { @class = "form-check-label" })

                                        @*Other solution to probe
                                            <input type="checkbox" id="item-@Model.Categories[i].Id" name="Items[@i]" value="@Model.Countries[i].Selected" />
                                            <label for="item-@Model.Categories[i].Id">@Model.Categories[i].Name</label>*@
                                    </div>
                                </li>
                            }
                        </ul>
                        @Html.ValidationMessageFor(model => model.Categories, "", new { @class = "text-danger" })
                    </div>

                </div>
                <div class="col">
                    <div class="form-group mt-3 col-lg-7">
                        @Html.LabelFor(model => model.PlayerTypes, htmlAttributes: new { @class = "control-label" })
                        <ul class="list-group">
                            @for (int i = 0; i < Model.PlayerTypes.Count; i++)
                            {
                                <li class="list-group-item">
                                    <div class="form-check form-switch">
                                        @Html.HiddenFor(m => m.PlayerTypes[i].PlayerTypeId)
                                        @Html.HiddenFor(m => m.PlayerTypes[i].Type)
                                        @Html.CheckBoxFor(m => m.PlayerTypes[i].Selected, new { @class = "form-check-input", @type = "checkbox", @role = "switch" })
                                        @Html.LabelFor(m => m.PlayerTypes[i].Selected, Model.PlayerTypes[i].Type, new { @class = "form-check-label" })

                                        @*Other solution to probe
                                            <input type="checkbox" id="item-@Model.PlayerTypes[i].PlayerTypeId" name="Items[@i]" value="@Model.PlayersType[i].Selected" />
                                            <label for="item-@Model.PlayerTypes[i].Id">@Model.PlayerTypes[i].Type</label>*@
                                    </div>
                                </li>
                            }
                        </ul>
                        @Html.ValidationMessageFor(model => model.PlayerTypes, "", new { @class = "text-danger w-25" })
                    </div>
                </div>
            </div>
        </div>
        <div class="mb-lg-5 mt-3">
            @Html.LabelFor(model => model.imageFile, htmlAttributes: new { @class = "form-label col-4" })
            @Html.TextBoxFor(modelo => modelo.imageFile, new { @class = "form-control col-12", @type = "file" })
        </div>
        <div class="mt-3">
            <button class="btn btn-sm btn-outline-primary bg-primary bg-opacity-10 col-3 me-2" type="submit">
                <i class="fa fa-check"></i>
                Add
            </button>
            @*<input type="submit" value="Add" class="btn btn-sm btn-outline-primary bg-primary bg-opacity-10 col-3 me-2" />*@

            <a class="btn btn-sm btn-outline-danger bg-danger bg-opacity-10 col-3" href="@Url.Action($"Index","Games")">
                <i class="fa fa-undo"></i>
                Cancel
            </a>
            @*@Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-sm btn-outline-danger bg-danger bg-opacity-10 col-3" })*@
        </div>

    </div>
}

KMGames.Web/Views/Games/Delete.cshtml
@model KMGames.Web.ViewModel.Games.GameListVm

@{
    ViewBag.Title = "Delete";
}

@Html.HiddenFor(model => model.GameId)
@Html.HiddenFor(model => model.RowVersion)

<h3>You are going to delete this game:</h3>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActualPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActualPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Release)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Release)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Developer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Developer)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color mt-3">

            <button class="btn btn-sm btn-outline-warning bg-warning bg-opacity-10 col-1 me-2" type="submit">
                <i class="fa fa-trash-alt"></i>
                Delete
            </button>
            @*<input type="submit" value="Delete" class="btn btn-sm btn-outline-warning bg-warning bg-opacity-10 col-1 me-2" />*@

            <a class="btn btn-sm btn-outline-danger bg-danger bg-opacity-10 col-1" href="@Url.Action($"Index","Games")">
                <i class="fa fa-undo"></i>
                Cancel
            </a>
            @*@Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-sm btn-outline-danger bg-danger bg-opacity-10 col-1" })*@
        </div>
    }
</div>

KMGames.Web/Views/Games/Edit.cshtml
@model KMGames.Web.ViewModel.Games.GameEditVm
@{

    ViewBag.Title = "Edit";
}

<h2>Edit game</h2>

@using (Html.BeginForm("Edit", "Games", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.GameId)
    @Html.HiddenFor(model => model.RowVersion)
    @Html.HiddenFor(model => model.Image)

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="mt-3 text-start align-content-start">
            <div class="row">
                <div class="col">
                    <div class="form-group mt-3">
                        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group mt-3">
                        @Html.LabelFor(model => model.ActualPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ActualPrice, new { htmlAttributes = new { @class = "form-control", } })
                            @Html.ValidationMessageFor(model => model.ActualPrice, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group mt-3">
                        @Html.LabelFor(model => model.Release, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div>
                            @Html.TextBoxFor(model => model.Release, "{0:yyyy-MM-dd}", new
                            {
                                @class = "form-control",
                                @Type = "date"
                                //@value = D,
                                //@min = "2018-06-07T00:00",
                                //@max = DateTime.Today.ToShortDateString()
                            })
                            @Html.ValidationMessageFor(model => model.Release, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group mt-3">
                        @Html.LabelFor(model => model.DeveloperId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.DeveloperId, Model.Developers, "Select a developer", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.DeveloperId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group mt-3 col-lg-7">
                        @Html.LabelFor(model => model.Categories, htmlAttributes: new { @class = "control-label" })
                        <ul class="list-group">
                            @for (int i = 0; i < Model.Categories.Count; i++)
                            {
                                <li class="list-group-item">
                                    <div class="form-check form-switch">
                                        @Html.HiddenFor(m => m.Categories[i].CategoryId)
                                        @Html.HiddenFor(m => m.Categories[i].Category)
                                        @Html.CheckBoxFor(m => m.Categories[i].Selected, new { @class = "form-check-input", @type = "checkbox", @role = "switch" })
                                        @Html.LabelFor(m => m.Categories[i].Selected, Model.Categories[i].Category, new { @class = "form-check-label" })

                                        @*Other solution to probe
                                            <input type="checkbox" id="item-@Model.Categories[i].Id" name="Items[@i]" value="@Model.Countries[i].Selected" />
                                            <label for="item-@Model.Categories[i].Id">@Model.Categories[i].Name</label>*@
                                    </div>
                                </li>
                            }
                        </ul>
                        @Html.ValidationMessageFor(model => model.Categories, "", new { @class = "text-danger" })
                    </div>

                </div>
                <div class="col">
                    <div class="form-group mt-3 col-lg-7">
                        @Html.LabelFor(model => model.PlayerTypes, htmlAttributes: new { @class = "control-label" })
                        <ul class="list-group">
                            @for (int i = 0; i < Model.PlayerTypes.Count; i++)
                            {
                                <li class="list-group-item">
                                    <div class="form-check form-switch">
                                        @Html.HiddenFor(m => m.PlayerTypes[i].PlayerTypeId)
                                        @Html.HiddenFor(m => m.PlayerTypes[i].Type)
                                        @Html.CheckBoxFor(m => m.PlayerTypes[i].Selected, new { @class = "form-check-input", @type = "checkbox", @role = "switch" })
                                        @Html.LabelFor(m => m.PlayerTypes[i].Selected, Model.PlayerTypes[i].Type, new { @class = "form-check-label" })

                                        @*Other solution to probe
                                            <input type="checkbox" id="item-@Model.PlayerTypes[i].PlayerTypeId" name="Items[@i]" value="@Model.PlayersType[i].Selected" />
                                            <label for="item-@Model.PlayerTypes[i].Id">@Model.PlayerTypes[i].Type</label>*@
                                    </div>
                                </li>
                            }
                        </ul>
                        @Html.ValidationMessageFor(model => model.PlayerTypes, "", new { @class = "text-danger w-25" })
                    </div>
                </div>
            </div>
        </div>

        <div class="mb-lg-5 mt-3">
            @Html.LabelFor(model => model.imageFile, htmlAttributes: new { @class = "form-label col-4" })
            @Html.TextBoxFor(modelo => modelo.imageFile, new { @class = "form-control col-12", @type = "file" })
        </div>

        <div class="form-group mt-3">
            <div class="col-md-offset-2 col-md-10">

                <button class="btn btn-sm btn-outline-success bg-success bg-opacity-10 col-3 me-2" type="submit">
                    <i class="fa fa-feather-alt"></i>
                    Edit
                </button>
                @*<input type="submit" value="Edit" class="btn btn-sm btn-outline-success bg-sucess bg-opacity-10 col-3 me-2" />*@

                <a class="btn btn-sm btn-outline-danger bg-danger bg-opacity-10 col-3" href="@Url.Action($"Index","Games")">
                    <i class="fa fa-undo"></i>
                    Cancel
                </a>
                @*@Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-sm btn-outline-danger bg-danger bg-opacity-10 col-3" })*@
            </div>
        </div>
    </div>
}

KMGames.Web/Views/Games/Index.cshtml
@using PagedList.Mvc

@model PagedList.IPagedList<KMGames.Web.ViewModel.Games.GameListVm>

@{
    ViewBag.Title = "Index";
}

@*@if (TempData.Keys.Contains("Success"))
    {
    <div class="alert alert-success alert-dismissible fade show w-75 bg-opacity-100" role="alert">
        @TempData["Success"].ToString()
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    }
    else if (TempData.Keys.Contains("Error"))
    {
    <div class="alert alert-danger alert-dismissible fade show w-75 bg-opacity-100" role="alert">
        @TempData["Error"].ToString()
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    }*@

<div class="d-flex justify-content-between">
    <h2>Games</h2>

    <a class="btn btn-outline-light bg-secondary bg-opacity-25" href="@Url.Action("Create","Games")">
        <i class="fa fa-plus"></i>
        New
    </a>

    <!--<p>-->
    @*@Html.ActionLink("New", "Create", null, new { @class = "btn btn-outline-light bg-secondary bg-opacity-25" })*@
    <!--</p>-->
</div>

@using (Html.BeginForm())
{

    <div class="row mt-3">
        <div class="col-auto">
            <label>Number per page:</label>
        </div>
        <div class="col-auto">
            <select name="PageSize" class="form-select">
                <option @if ((int)ViewBag.PageSize == 5) { @Html.Raw("selected") } value="5">5</option>
                <option @if ((int)ViewBag.PageSize == 10) { @Html.Raw("selected") } value="10">10</option>
                <option @if ((int)ViewBag.PageSize == 15) { @Html.Raw("selected") } value="15">15</option>
                <option @if ((int)ViewBag.PageSize == 20) { @Html.Raw("selected") } value="20">20</option>
            </select>
        </div>
        <div class="col-auto">
            <button class="btn btn-sm btn-outline-light bg-secondary" type="submit">
                <i class="fa fa-search"></i>
                Apply
            </button>
        </div>
    </div>
}

@if (Model.Any())
{
    <table class="table" style="color: #dee2e6">

        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().ActualPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Release)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Developer)
                </th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ActualPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Release)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Developer)
                    </td>
                    <td align="right">
                        <a class="btn btn-sm btn-outline-success bg-success bg-opacity-10 col-4" href="@Url.Action("Edit","Games", new { id = item.GameId })">
                            <i class="fa fa-feather-alt"></i>
                            Edit
                        </a>
                        @*@Html.ActionLink("Edit", "Edit", new { id = item.GameId }, new { @class = "btn btn-sm btn-outline-success bg-success bg-opacity-10 col-3" })*@

                        @*<a class="btn btn-sm btn-outline-info bg-primary bg-opacity-10" href="@Url.Action("Details","Games", new { id = item.GameId })">
                                <i class="fa fa-info"></i>
                                Details
                            </a>*@

                        @*@Html.ActionLink("Details", "Details", new { id = item.GameId }, new { @class = "btn btn-sm btn-outline-info bg-primary bg-opacity-10" })*@

                        <a class="btn btn-sm btn-outline-danger bg-danger bg-opacity-10" href="@Url.Action("Delete","Games", new { id = item.GameId })">
                            <i class="fa fa-trash-alt"></i>
                            Delete
                        </a>
                        @*@Html.ActionLink("Delete", "Delete", new { id = item.GameId }, new { @class = "btn btn-sm btn-outline-danger bg-danger bg-opacity-10" })*@
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-dark align-items-center d-flex w-75" role="alert">
        There's no game yet.
    </div>
}

Página: @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de: @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new
{
    page,
    pageSize = ViewBag.PageSize
}))