KMGames.Web/Controllers/CountriesController.cs
using AutoMapper;
using KMGames.Entities.Entities;
using KMGames.Services.Interfaces;
using KMGames.Web.App_Start;
using KMGames.Web.ViewModel.Cities;
using KMGames.Web.ViewModel.Country;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace KMGames.Web.Controllers
{
    [Authorize]
    public class CountriesController : Controller
    {
        //----------PROPERTIES-----------//

        private readonly ICountryService _countryService;
        private readonly ICityService _cityService;
        private readonly IMapper _mapper;

        //----------CONTRUCTOR----------//

        public CountriesController(ICountryService countryService, ICityService cityService)
        {
            _countryService = countryService;
            _cityService = cityService;
            _mapper = AutoMapperConfig.Mapper;
        }

        // GET: Countries
        public ActionResult Index(int? page, int? pageSize)
        {
            var countriesList = _countryService.GetCountries();

            var listVm = _mapper.Map<List<CountryListVm>>(countriesList);

            page = page ?? 1;
            pageSize = pageSize ?? 10;

            ViewBag.PageSize = pageSize;

            return View(listVm.ToPagedList(page.Value,pageSize.Value));
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CountryEditVm countryEditVm)
        {
            if (!ModelState.IsValid)
            {
                return View(countryEditVm);
            }

            var country = _mapper.Map<Country>(countryEditVm);

            if (_countryService.Exist(country))
            {
                ModelState.AddModelError(string.Empty,$"There already exists a country with {country.Name} name.");
                return View(countryEditVm);
            }

            _countryService.Add(country);

            TempData["Success"] = "SUCCESS: Country saved successfully";

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int? id)
        {
            if(id is null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var country = _countryService.GetCountry(id.Value);

            if(country is null)
            {
                TempData["Error"] = "ERROR: The country was deleted by other user.";

                return RedirectToAction("Index");
            }
            else if (_countryService.ItsRelated(country))
            {
                TempData["Error"] = $"ERROR: {country.Name} it's related to some data. It can't be deleted";

                return RedirectToAction("Index");
            }
            else
            {
                var countryListVm = _mapper.Map<CountryListVm>(country);

                return View(countryListVm);
            }
        }

        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var country = _countryService.GetCountry(id);

            _countryService.Delete(country);

            TempData["Warning"] = $"WARNING: {country.Name} removed successfully.";

            return RedirectToAction("Index");
        }


        public ActionResult Edit(int? id)
        {
            if(id is null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var country = _countryService.GetCountry(id.Value);

            if(country is null)
            {
                TempData["Error"] = "ERROR: The country was deleted by other user.";

                return RedirectToAction("Index");
            }

            var countryEditVm = _mapper.Map<CountryEditVm>(country);

            return View(countryEditVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CountryEditVm countryEditVm)
        {
            if (!ModelState.IsValid)
            {
                return View(countryEditVm);
            }

            var country = _mapper.Map<Country>(countryEditVm);

            if (_countryService.Exist(country))
            {
                ModelState.AddModelError(string.Empty, "There alredy exist a country with that name.");

                return View(countryEditVm);
            }

            _countryService.Edit(country);

            TempData["Success"] = "SUCCESS: Country edited successfully";

            return RedirectToAction("Index");
        }

        public ActionResult Details(int? id)
        {
            if(id is null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var country = _countryService.GetCountry(id.Value);

            if (country is null)
            {
                TempData["Error"] = "ERROR: The country was deleted by other user.";

                return RedirectToAction("Index");
            }

            var countryListVm = _mapper.Map<CountryListVm>(country);

            var cityListVm = _mapper.Map<List<CityListVm>>(_cityService.GetCities(country.CountryId));

            var countryDetails = new CountryDetailsVm()
            {
                Country = countryListVm,
                Cities = cityListVm
            };

            return View(countryDetails);
        }

        public ActionResult AddCity(int? countryId)
        {
            if (countryId is null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var country = _countryService.GetCountry(countryId.Value);

            if (country is null)
            {
                TempData["Error"] = "ERROR: The country was deleted by other user.";

                return RedirectToAction($"/Details/{countryId.Value}");
            }

            var cityEditVm = new CityEditVm()
            {
                CountryId = countryId.Value,
                Countries = _countryService.GetDropDownList()
            };

            return View(cityEditVm);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCity(CityEditVm cityEditVm)
        {
            if (!ModelState.IsValid)
            {
                cityEditVm.Countries = _countryService.GetDropDownList();

                return View(cityEditVm);
            }

            var city = _mapper.Map<City>(cityEditVm);

            if (_cityService.Exist(city))
            {
                ModelState.AddModelError(string.Empty, $"{cityEditVm.Name} already exist in the selected country.");

                cityEditVm.Countries = _countryService.GetDropDownList();

                return View(cityEditVm);
            }

            try
            {
                _cityService.Add(city);

                TempData["Success"] = "SUCCESS: City added successfully";
            }
            catch(Exception ex)
            {
                TempData["Error"] = $"ERROR: An error ocurred while trying to add a new city.\n{ex.Message}";
            }
            
            return RedirectToAction($"/Details/{cityEditVm.CountryId}");
        }

        public ActionResult DeleteCity(int? cityId)
        {
            if (cityId is null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var city = _cityService.GetCity(cityId.Value);

            if (city is null)
            {
                TempData["Error"] = "ERROR: The city was deleted by other user.";

                return RedirectToAction($"Index");
            }
            else if (_cityService.ItsRelated(cityId.Value))
            {
                TempData["Error"] = "ERROR: The city is related to some developers. It can't be deleted.";

                return RedirectToAction($"/Details/{city.CountryId}");
            }

            var cityEditVm = _mapper.Map<CityEditVm>(city);

            cityEditVm.Countries = _countryService.GetDropDownList();

            return View(cityEditVm);
        }

        [HttpPost,ActionName("DeleteCity")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteCity(int cityId)
        {
            var city = _cityService.GetCity(cityId);

            _cityService.Delete(city);

            TempData["Warning"] = $"WARNING: {city.Name} was deleted from database.";

            return RedirectToAction($"/Details/{city.CountryId}");
        }

        public ActionResult EditCity(int? cityId)
        {
            if (cityId is null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var city = _cityService.GetCity(cityId.Value);

            if (city is null)
            {
                TempData["Error"] = "ERROR: The city was deleted by other user.";

                return RedirectToAction($"/Details/{city.CountryId}");
            }

            var cityEditVm = _mapper.Map<CityEditVm>(city);

            cityEditVm.Countries = _countryService.GetDropDownList();

            return View(cityEditVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCity(CityEditVm cityEditVm)
        {
            if (!ModelState.IsValid)
            {
                cityEditVm.Countries = _countryService.GetDropDownList();

                return View(cityEditVm);
            }

            var city = _mapper.Map<City>(cityEditVm);

            if (_cityService.Exist(city))
            {
                ModelState.AddModelError(string.Empty, $"{cityEditVm.Name} already exist in the selected country.");

                cityEditVm.Countries = _countryService.GetDropDownList();

                return View(cityEditVm);
            }

            try
            {

KMGames.Web/Views/Countries/AddCity.cshtml
@model KMGames.Web.ViewModel.Cities.CityEditVm

@{
    ViewBag.Title = "AddCity";
}

<h2>Add city for</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.CountryId)

    <div class="form-horizontal">
        <hr />

        <div class="form-group mt-3">
            @Html.LabelFor(model => model.CountryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CountryId, Model.Countries, "Select a country", new { @class = "form-control", @disabled = "disabled"})
                @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group mt-3">
            <div class="col-md-offset-2 col-md-10">
                <button class="btn btn-outline-primary bg-opacity-10 bg-primary btn-sm col-1 me-2" type="submit">
                    <i class="fa fa-check"></i>
                    Add
                </button>
                @*<input type="submit" value="Add" class="btn btn-sm btn-outline-primary bg-primary bg-opacity-10 col-1 me-2" />*@

                <a class="btn btn-sm btn-outline-danger bg-danger bg-opacity-10 col-1" href="@Url.Action($"/Details/{Model.CountryId}","Countries")">
                    <i class="fa fa-undo"></i>
                    Cancel
                </a>
                @*@Html.ActionLink("Cancel", $"Details/{Model.CountryId}", null, new { @class = "btn btn-sm btn-outline-danger bg-danger bg-opacity-10 col-1" })*@
            </div>
        </div>
    </div>
}

KMGames.Web/Views/Countries/Create.cshtml
@model KMGames.Web.ViewModel.Country.CountryEditVm

@{
    ViewBag.Title = "Create";
}

<h2>Add country</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control col-4" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mt-3">
            <div class="col-md-offset-2 col-md-10 justify-content-center">
                <button class="btn btn-outline-primary bg-opacity-10 bg-primary btn-sm col-1 me-2" type="submit">
                    <i class="fa fa-check"></i>
                    Add
                </button>
                @*<input type="submit" value="Add" class="btn btn-outline-primary bg-opacity-10 bg-primary btn-sm col-1 me-2" />*@

                <a class="btn btn-sm btn-outline-danger bg-danger bg-opacity-10 col-1" href="@Url.Action("Index","Countries")">
                    <i class="fa fa-undo"></i>
                    Cancel
                </a>
                @*@Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-outline-danger bg-opacity-10 bg-danger btn-sm col-1" })*@
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KMGames.Web/Views/Countries/Delete.cshtml
@model KMGames.Web.ViewModel.Country.CountryListVm

@{
    ViewBag.Title = "Delete";
}

<h3>You are going to delete this country :</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd class="mt-2">
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button class="btn btn-sm btn-outline-warning bg-warning bg-opacity-10 col-1 me-2">
                <i class="fa fa-trash-alt"></i>
                Delete
            </button>
            @*<input type="submit" value="Delete" class="btn btn-outline-warning bg-opacity-10 bg-warning btn-sm col-1 me-2" />*@

            <a class="btn btn-sm btn-outline-danger bg-danger bg-opacity-10 col-1" href="@Url.Action("Index","Countries")">
                <i class="fa fa-undo"></i>
                Cancel
            </a>
            @*@Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-outline-danger bg-opacity-10 bg-danger btn-sm col-1" })*@
        </div>
    }
</div>

KMGames.Web/Views/Countries/DeleteCity.cshtml
@model KMGames.Web.ViewModel.Cities.CityEditVm

@{
    ViewBag.Title = "DeleteCity";
}

<h3>You are going to delete this city from: </h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CountryId)
        </dt>

        <dd>
            @Html.DropDownListFor(model => model.CountryId, Model.Countries, new { @class = "form-control", @disabled = "disabled" })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @disabled = "disabled" })
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color mt-3">
            <button class="btn btn-sm btn-outline-warning bg-warning bg-opacity-10 col-1 me-2">
                <i class="fa fa-trash-alt"></i>
                Delete
            </button>

            @*<input type="submit" value="Delete" class="btn btn-sm btn-outline-warning bg-warning bg-opacity-10 col-1 me-2" />*@

            <a class="btn btn-sm btn-outline-danger bg-danger bg-opacity-10 col-1" href="@Url.Action($"/Details/{Model.CountryId}","Countries")">
                <i class="fa fa-undo"></i>
                Cancel
            </a>
            @*@Html.ActionLink("Cancel", $"/Details/{Model.CountryId}", null, new { @class = "btn btn-sm btn-outline-danger bg-danger bg-opacity-10 col-1" })*@
        </div>
    }
</div>

KMGames.Web/Views/Countries/Details.cshtml
@model KMGames.Web.ViewModel.Country.CountryDetailsVm

@{
    ViewBag.Title = "Details";
}

<div class="h2">
    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.Country.Name)
        </dt>

        <dd class="mt-2">
            @Html.TextBoxFor(model => model.Country.Name, new { @class = "form-control", @disabled = "disabled" })
        </dd>
    </dl>
    <a class="btn btn-sm btn-outline-primary bg-primary bg-opacity-10 col-1 me-2" href="@Url.Action("AddCity","Countries",new { countryId = Model.Country.CountryId })">
        <i class="fa fa-check"></i>
        Add City
    </a>
    @*@Html.ActionLink("Add City", "AddCity", new { countryId = Model.Country.CountryId }, new { @class = "btn btn-sm btn-outline-primary bg-primary bg-opacity-10 col-1 me-2" })*@
    
    <a class="btn btn-sm btn-outline-danger bg-danger bg-opacity-10 col-1" href="@Url.Action("Index","Countries")">
        <i class="fa fa-undo"></i>
        Go Back
    </a>
    @*@Html.ActionLink("Go Back", "Index", null, new { @class = "btn btn-sm btn-outline-danger bg-danger bg-opacity-10 col-1" })*@
</div>

<hr />

@if (Model.Cities.Any())
{

    <table class="table w-50" style="color: #dee2e6;">

        <thead>
            <tr>
                <th class="w-25">
                    @Html.DisplayNameFor(model => model.Cities.FirstOrDefault().Name)
                </th>
                <th class="w-25" style="text-align:left">
                    Actions 
                </th>
            </tr>
        </thead>

        <tbody class="table-group-divider">
            @foreach (var item in Model.Cities)
            {
                <tr>
                    <td class="w-25">
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td class="w-25" align="left">
                        <a class="btn btn-sm btn-outline-success bg-success bg-opacity-10 col-3" href="@Url.Action("EditCity","Countries",new { cityId = item.CityId })">
                            <i class="fa fa-feather-alt"></i>
                            Edit
                        </a>
                        @*@Html.ActionLink("Edit", "EditCity", new { cityId = item.CityId }, new { @class = "btn btn-sm btn-outline-success bg-success bg-opacity-10 col-3" })*@

                        <a class="btn btn-sm btn-outline-danger bg-opacity-10 bg-danger" href="@Url.Action("DeleteCity","Countries",new { cityId = item.CityId })">
                            <i class="fa fa-trash-alt"></i>
                            Delete
                        </a>
                        @*@Html.ActionLink("Delete", "DeleteCity", new { cityid = item.CityId }, new { @class = "btn btn-sm btn-outline-danger bg-danger bg-opacity-10" })*@
                    </td>
                </tr>
            }
        </tbody>

    </table>
}
else
{
    <div class="d-flex alert alert-dark align-items-center w-75 " role="alert">
        There's no city yet.
    </div>
}

KMGames.Web/Views/Countries/Edit.cshtml
@model KMGames.Web.ViewModel.Country.CountryEditVm

@{
    ViewBag.Title = "Edit";
}

<h2>Edit country</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CountryId)
        @Html.HiddenFor(model => model.RowVersion)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 mt-3">
                <button class="btn btn-sm btn-outline-success bg-success bg-opacity-10 col-1 me-2">
                    <i class="fa fa-feather-alt"></i>
                    Edit
                </button>
                @*<input type="submit" value="Edit" class="btn btn-sm btn-outline-success bg-success bg-opacity-25 col-1 me-2" />*@

                <a class="btn btn-sm btn-outline-danger bg-danger bg-opacity-10 col-1" href="@Url.Action("Index","Countries")">
                    <i class="fa fa-undo"></i>
                    Cancel
                </a>
                @*@Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-sm btn-outline-danger bg-danger bg-opacity-25 col-1" })*@
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KMGames.Web/Views/Countries/EditCity.cshtml
@model KMGames.Web.ViewModel.Cities.CityEditVm

@{
    ViewBag.Title = "EditCity";
}

<h2>Edit city for</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.CityId)
    @Html.HiddenFor(model => model.RowVersion)
    @Html.HiddenFor(model => model.CountryId)

    <div class="form-horizontal">
        <hr />
        <div class="form-group mt-3">
            @Html.LabelFor(model => model.CountryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CountryId, Model.Countries, "Select a country", new { @class = "form-control", @disabled="disabled" })
                @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group mt-3">
            <div class="col-md-offset-2 col-md-10">
                <button class="btn btn-sm btn-outline-success bg-success bg-opacity-10 col-1 me-2">
                    <i class="fa fa-feather-alt"></i>
                    Edit
                </button>
                @*<input type="submit" value="Edit" class="btn btn-sm btn-outline-success bg-success bg-opacity-10 col-1 me-2" />*@

                <a class="btn btn-sm btn-outline-danger bg-danger bg-opacity-10 col-1" href="@Url.Action($"/Details/{Model.CountryId}","Countries")">
                    <i class="fa fa-undo"></i>
                    Cancel
                </a>
                @*@Html.ActionLink("Cancel", $"/Details/{Model.CountryId}", null, new { @class = "btn btn-sm btn-outline-danger bg-danger bg-opacity-10 col-1" })*@
            </div>
        </div>
    </div>
}

KMGames.Web/Views/Countries/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<KMGames.Web.ViewModel.Country.CountryListVm>

@{
    ViewBag.Title = "Index";
}


@*@if (TempData["Msg"] != null)
    {
        <div class="alert alert-success alert-dismissible fade show w-75 bg-opacity-100" role="alert">
            @TempData["Msg"].ToString()
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }*@

<div class="d-flex justify-content-between w-75">

    <h2>Countries</h2>

    <a class="btn btn-outline-light bg-opacity-25 bg-secondary" href="@Url.Action("Create","Countries")">
        <i class="fa fa-plus"></i>
        New
    </a>

    @*<p>
            @Html.ActionLink("New", "Create", null, new { @class = "btn btn-outline-light bg-opacity-25 bg-secondary" })
        </p>*@

</div>


@using (Html.BeginForm())
{

    <div class="row mt-3">
        <div class="col-auto">
            <label>Number per page:</label>
        </div>
        <div class="col-auto">
            <select name="PageSize" class="form-select">
                <option @if ((int)ViewBag.PageSize == 5) { @Html.Raw("selected") } value="5">5</option>
                <option @if ((int)ViewBag.PageSize == 10) { @Html.Raw("selected") } value="10">10</option>
                <option @if ((int)ViewBag.PageSize == 15) { @Html.Raw("selected") } value="15">15</option>
                <option @if ((int)ViewBag.PageSize == 20) { @Html.Raw("selected") } value="20">20</option>
            </select>
        </div>
        <div class="col-auto">
            <button class="btn btn-sm btn-outline-light bg-secondary" type="submit">
                <i class="fa fa-search"></i>
                Apply
            </button>
        </div>
    </div>
}

@if (Model.Any())
{
    <table class="table w-75" style="color: #dee2e6">
        <thead>
            <tr>
                <th class="w-50">
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Name)
                </th>
                <th class="w-25"></th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td align="right">
                        <a class="btn btn-sm btn-outline-success bg-success bg-opacity-10 col-4" href="@Url.Action("Edit","Countries",new { id = item.CountryId })">
                            <i class="fa fa-feather-alt"></i>
                            Edit
                        </a>
                        @*@Html.ActionLink("Edit", "Edit", new { id = item.CountryId }, new { @class = "btn btn-sm btn-outline-success bg-opacity-10 bg-info col-3" })*@

                        <a class="btn btn-sm btn-outline-info bg-opacity-10 bg-primary" href="@Url.Action("Details","Countries",new { id = item.CountryId })">
                            <i class="fa fa-bars"></i>
                            Details
                        </a>
                        @*@Html.ActionLink("Details", "Details", new { id = item.CountryId }, new { @class = "btn btn-sm btn-outline-info bg-opacity-25 bg-primary" })*@

                        <a class="btn btn-sm btn-outline-danger bg-opacity-10 bg-danger" href="@Url.Action("Delete","Countries",new { id = item.CountryId })">
                            <i class="fa fa-trash-alt"></i>
                            Delete
                        </a>
                        @*@Html.ActionLink("Delete", "Delete", new { id = item.CountryId }, new { @class = "btn btn-sm btn-outline-danger bg-opacity-10 bg-danger" })*@
                    </td>
                </tr>
            }
        </tbody>

    </table>
}
else
{
    <div class="alert alert-dark d-flex align-items-center w-75" role="alert">
        There's no country yet.
    </div>
}

Página: @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de: @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new
{
    page,
    pageSize = ViewBag.PageSize
}))